name: Apply Sentinel policies for Azure

concurrency:
  group: terraform

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  SENTINEL_VERSION: 0.40.0
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.PLAN_AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Install HashiCorp Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Initialize Terraform configuration
        run: terraform init
      - name: Create Terraform plan output
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -json tfplan | jq > tfplan.json
      
      - name: Checkout Sentinel policy repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/sentinel-policies
          path: sentinel-policies
      - name: Copy Terraform plan output
        run: cp tfplan.json sentinel-policies/
      - name: Install HashiCorp Sentinel
        run: |
          FILENAME="sentinel_${{ env.SENTINEL_VERSION }}_linux_amd64.zip"
          wget "https://releases.hashicorp.com/sentinel/${{ env.SENTINEL_VERSION }}/$FILENAME"
          unzip "$FILENAME" -d $HOME/bin
          chmod +x $HOME/bin/sentinel
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Run HashiCorp Sentinel
        run: sentinel apply
        working-directory: sentinel-policies